### ISSUE TITLE
Dependency error on Python 3.12

### ISSUE THREAD

**Issue by satwikkansal** [OrderlyNetwork/orderly-evm-connector-python#20]
```shell
$ pip install git+https://github.com/OrderlyNetwork/orderly-evm-connector-
```

Error
```
python.git@794072bdf91abdfdcd373cc2d86909b7687ce63e
Collecting git+https://github.com/OrderlyNetwork/orderly-evm-connector-python.git@794072bdf91abdfdcd373cc2d86909b7687ce63e
  Cloning https://github.com/OrderlyNetwork/orderly-evm-connector-python.git (to revision 794072bdf91abdfdcd373cc2d86909b7687ce63e) to /tmp/pip-req-build-7u5lwuax
  Running command git clone --filter=blob:none --quiet https://github.com/OrderlyNetwork/orderly-evm-connector-python.git /tmp/pip-req-build-7u5lwuax
  Running command git rev-parse -q --verify 'sha^794072bdf91abdfdcd373cc2d86909b7687ce63e'
  Running command git fetch -q https://github.com/OrderlyNetwork/orderly-evm-connector-python.git 794072bdf91abdfdcd373cc2d86909b7687ce63e
  Resolved https://github.com/OrderlyNetwork/orderly-evm-connector-python.git to commit 794072bdf91abdfdcd373cc2d86909b7687ce63e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: aiohttp<4.0.0,>=3.9.5 in ./.venv/lib/python3.12/site-packages (from orderly-evm-connector==0.1.1) (3.10.5)
Collecting asgiref<4.0.0,>=3.8.1 (from orderly-evm-connector==0.1.1)
  Using cached asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting base58<3.0.0,>=2.1.1 (from orderly-evm-connector==0.1.1)
  Using cached base58-2.1.1-py3-none-any.whl.metadata (3.1 kB)
Collecting cryptography<43.0.0,>=42.0.8 (from orderly-evm-connector==0.1.1)
  Using cached cryptography-42.0.8-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting ed25519<2.0,>=1.5 (from orderly-evm-connector==0.1.1)
  Using cached ed25519-1.5.tar.gz (868 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /tmp/pip-install-1n2gkhyf/ed25519_a7e8b5e24f114b7999637e1ad61a3fe2/versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/root/liquidity-sniper/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/liquidity-sniper/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/liquidity-sniper/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wbgd1l9w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wbgd1l9w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-wbgd1l9w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-wbgd1l9w/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 115, in <module>
        File "/tmp/pip-install-1n2gkhyf/ed25519_a7e8b5e24f114b7999637e1ad61a3fe2/versioneer.py", line 1405, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-1n2gkhyf/ed25519_a7e8b5e24f114b7999637e1ad61a3fe2/versioneer.py", line 1339, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-1n2gkhyf/ed25519_a7e8b5e24f114b7999637e1ad61a3fe2/versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by kennnnliu** [comment]
could u try to use pip to install, instead of from github

**Comment by satwikkansal** [comment]
I am getting same error. This might be related: https://github.com/pydata/pandas-datareader/issues/969

**Comment by kennnnliu** [comment]
did u try to use poetry shell?
maybe ur env issue
